#!/bin/bash

set -xe

source /etc/profile

mkdir -p "$HOME/.x11vnc"
PASSWD_PATH="$HOME/.x11vnc/passwd"

rm -rf /tmp/.X1-lock /tmp/.X11-unix/X1

$NOVNC_HOME/utils/launch.sh --vnc localhost:$VNC_PORT --listen $NOVNC_PORT &
Xvfb $DISPLAY -screen 0 "$VNC_RESOLUTION"x"$VNC_COL_DEPTH" &
startxfce4 --replace > $HOME/wm.log 2>&1 &

wget -N -O /app/iptvboss.jar "https://www.dropbox.com/s/9exgd43rxatcjkm/IPTVBoss.jar?dl=1"
  
if [ ! -f /app/config.yaml ]; then
  echo "sceneHeight: 936.0" > /app/config.yaml
  echo "sceneWidth: 1270.0" >> /app/config.yaml
fi
if [ ! -f $HOME/appinit.sh ]; then
  echo "#!/bin/bash" > $HOME/appinit.sh
  echo "killall java" >> $HOME/appinit.sh
  echo "cd /app;java -jar iptvboss.jar -noGui" >> $HOME/appinit.sh
  echo "cd /app;java -jar iptvboss.jar &" >> $HOME/appinit.sh
  chmod +x -v $HOME/appinit.sh
fi
sleep 1
x11vnc -xkb -noxrecord -noxfixes -noxdamage -permitfiletransfer -tightfilexfer -display $DISPLAY -forever -o $HOME/.x11vnc/x11vnc.log -bg && tail -f $HOME/.x11vnc/x11vnc.log
